name: autofix.ci

on:
  pull_request:
    branches-ignore:
      - 'renovate/**'
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  apply:
    name: Apply automated fixes
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'renovate[bot]' && ! contains(github.event.head_commit.author.name , 'renovate[bot]') && ! contains(github.event.head_commit.message , 'chore(release)') }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup toolchains
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - name: Setup Aikido Safe Chain
        run: curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh -s -- --ci
      - name: Install dependencies
        run: bun install
      - name: Format code
        run: bun biome check --write
      - name: Fix package.json
        run: bun syncpack fix
      - name: Format package.json
        run: bun syncpack format
      - name: Update lock file
        run: bun install
      - name: Submit autofix
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        with:
          fail-fast: false
